name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install
        
      - name: Build site
        working-directory: ./frontend
        run: pnpm run build

      - name: Install infrastructure dependencies
        working-directory: ./infrastructure
        run: pnpm install
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
        
      - name: Deploy infrastructure
        working-directory: ./infrastructure
        env:
          DEV_ACCESS_SECRET: ${{ secrets.DEV_ACCESS_SECRET }}
        run: |
          npx cdk deploy \
          --all \
          --require-approval never \
          --context environment=${{ github.event_name == 'release' && 'prod' || 'dev' }}
