name: Build and Deploy

name: Build and Deploy

env:
  SVELTE_BUILD: frontend/.svelte-kit/output/client

on:
  push:
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ${{ env.SVELTE_BUILD }}
          
  deploy-cdk:
    needs: build-frontend
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './infrastructure/package-lock.json'
          
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ${{ env.SVELTE_BUILD }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install CDK dependencies
        working-directory: ./infrastructure
        run: npm ci
        
      - name: Deploy with CDK
        working-directory: ./infrastructure
        run: |
          npx cdk deploy --all --require-approval never --context environment=${{ github.event_name == 'release' && 'prod' || 'dev' }}
